name: '🔄 Update Celebrity'
description: Create a new celebrity.
title: '🔄 [UPDATE CELEBRITY] - <name of the celebrity>'
labels: ['update-celebrity']
body:
  - type: input
    id: celebrity-id
    attributes:
      label: 'Celebrity ID'
      description: Please enter the celebrity's ID
      placeholder: ex. ali_karimi
    validations:
      required: true
  - type: input
    id: twitter-url
    attributes:
      label: 'New Twitter URL'
      description: If applicable, please enter the celebrity's new Twitter account URL
      placeholder: ex. https://twitter.com/alikarimi_ak8
    validations:
      required: false
  - type: input
    id: instagram-url
    attributes:
      label: 'New Instagram URL'
      description: If applicable, please enter the celebrity's new Instagram account URL
      placeholder: ex. https://instagram.com/aliiiiiiiikarimi8
    validations:
      required: false
  - type: dropdown
    id: status
    attributes:
      label: 'New Status'
      description: If applicable, what is the new status of the celebrity?
      multiple: false
      options:
        - Good
        - Bad
        - Ugly
    validations:
      required: false
  - type: input
    id: status-url
    attributes:
      label: 'New Status Reference URL'
      description: If they are not ugly, please enter the celebrity's content URL that indicates their status
      placeholder: ex. https://twitter.com/alikarimi_ak8/status/1574076531483312128?s=20&t=X57jDRgIBSmiU95GK8NvhA
    validations:
      required: false
